# Introduction to NumPy

## Why use NumPy?

1. Performance Improvements (Execution and Memory Useage)
1. More convenient math syntax
1. Enables vectorisation in low level `C`, `Fortran` code.

**Note:** For `data` work you will implicitly be using `numpy` through `pandas`.

### Pure Python

In [1]:
import random
length = 1000
a = [random.normalvariate(0,1) for x in range(length)]
b = [random.normalvariate(0,1) for x in range(length)]

**Question:** What is random.normalvariate?

In [2]:
random.normalvariate?

In [3]:
len(a), len(b)

(1000, 1000)

In [4]:
type(a), type(b)

(list, list)

In [5]:
# What is in list a
a

[-0.09140823329761712,
 -0.6956397787699828,
 -0.19553468956803988,
 -0.5496923878686933,
 0.1803327886810451,
 -0.3709502449925348,
 -2.132530570464149,
 0.3992911867093573,
 -0.02430325425569793,
 -0.8917459478473451,
 -1.1512975205559424,
 -0.08518254026668763,
 -1.1734330222887859,
 0.2630056540983286,
 -0.6755060092287812,
 -0.16182181696034087,
 0.037040944505463524,
 0.04683059447163162,
 -0.971944346972543,
 0.24055809638588946,
 -0.8093397022312369,
 -0.35161593605222735,
 -0.3312251317225448,
 -0.097121361602216,
 -0.26525526895333296,
 1.6658138962709215,
 -0.28025946036530924,
 0.08180605634254665,
 0.24245447659151617,
 1.1871307190190807,
 -0.5313829592156925,
 -1.0991441393507535,
 0.9663731349689183,
 0.7907917394772266,
 1.7464118428600193,
 -1.7310099507936583,
 0.21831257953367997,
 -0.6504883806905983,
 2.70667506023828,
 -2.1404394918933787,
 -1.4970844886802384,
 -0.8331794083195344,
 0.7493549970130824,
 0.162177268385001,
 -1.301718111536816,
 0.8765183330226023

In [6]:
# Find number of bytes used by list object 'a'
import sys
sys.getsizeof(a)

9016

Let's multiply each element between a and b

In [7]:
%%timeit
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])

152 µs ± 12 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## NumPy

Let us now do the same excercise using NumPy

In [8]:
import numpy as np
np_a = np.array(a)
np_b = np.array(b)

In [9]:
type(np_a)

numpy.ndarray

In [10]:
len(np_a)

1000

In [11]:
np_a.shape

(1000,)

In [12]:
# What is in the np_a array
np_a

array([-9.14082333e-02, -6.95639779e-01, -1.95534690e-01, -5.49692388e-01,
        1.80332789e-01, -3.70950245e-01, -2.13253057e+00,  3.99291187e-01,
       -2.43032543e-02, -8.91745948e-01, -1.15129752e+00, -8.51825403e-02,
       -1.17343302e+00,  2.63005654e-01, -6.75506009e-01, -1.61821817e-01,
        3.70409445e-02,  4.68305945e-02, -9.71944347e-01,  2.40558096e-01,
       -8.09339702e-01, -3.51615936e-01, -3.31225132e-01, -9.71213616e-02,
       -2.65255269e-01,  1.66581390e+00, -2.80259460e-01,  8.18060563e-02,
        2.42454477e-01,  1.18713072e+00, -5.31382959e-01, -1.09914414e+00,
        9.66373135e-01,  7.90791739e-01,  1.74641184e+00, -1.73100995e+00,
        2.18312580e-01, -6.50488381e-01,  2.70667506e+00, -2.14043949e+00,
       -1.49708449e+00, -8.33179408e-01,  7.49354997e-01,  1.62177268e-01,
       -1.30171811e+00,  8.76518333e-01,  7.95185657e-01,  5.17774963e-01,
       -1.09944994e+00, -1.17669595e+00, -9.56943490e-01, -1.08618784e+00,
        8.67625467e-01,  

In [13]:
# Get size of np_a array in bytes
np_a.nbytes

8000

In [14]:
%%timeit
np_c = np_a * np_b # Element by Element Operation for Multiply

1e+03 ns ± 29.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


**Question:** Why does this seem to take longer?

## Broadcasting

Broadcasting describes the absence of any explicit looping in `python`. 

Therefore you do not need to write explicit loops. 

In the code cell `above` the * operator performs the operations over the length of the arrays. 

In [15]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b                          # No Python Loop Required

array([2., 4., 6.])

NumPy has different behaviour when the **shapes of objects do not match**. 

For example, a `scalar` multiplied with an `array` will broadcase the operation along the array

**Documentation:** http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#module-numpy.doc.broadcasting

In [16]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

**Tip:** Using `numpy` is largely about learning how the operators behave in context

# NumPy Data Types

NumPy supports a much greater variety of numeric data types than Python does

| Data type |	Description |
| ----------|---------------|
| bool_ |	Boolean (True or False) stored as a byte |
| int_  |	Default integer type (same as C long; normally either int64 or int32) |
| intc  |	Identical to C int (normally int32 or int64) |
| intp	 | Integer used for indexing (same as C ssize_t; normally either int32 or int64) |
| int8	 | Byte (-128 to 127) |
| int16 | 	Integer (-32768 to 32767) |
| int32 | 	Integer (-2147483648 to 2147483647) |
| int64 | 	Integer (-9223372036854775808 to 9223372036854775807) |
| uint8 | 	Unsigned integer (0 to 255) |
| uint16 |	Unsigned integer (0 to 65535) |
| uint32 |	Unsigned integer (0 to 4294967295) |
| uint64 |	Unsigned integer (0 to 18446744073709551615) |
| float_ |	Shorthand for float64. |
| float16 |	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa |
| float32 |	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa |
| float64 |	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa |
| complex_ |	Shorthand for complex128. |
| complex64	| Complex number, represented by two 32-bit floats (real and imaginary components) |
| complex128 |	Complex number, represented by two 64-bit floats (real and imaginary components) |

**Documentation:** http://docs.scipy.org/doc/numpy/user/basics.types.html

In [17]:
#Default dtypes are typically float64, int64 on most recent platforms
a = np.arange(4)

In [18]:
type(a[0])

numpy.int64

In [19]:
a = np.arange(4.0)

In [20]:
type(a[0])

numpy.float64

## Array Creation

Arrays can be generated from python sequences such as a List

In [21]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = np.array([[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0]])

## Array Shapes

`NumPy` is really an n-dimensional (**nd**array), where vectors and matrices are just low dimensional cases

| Type | Dimension |
|---------|----------|
| Vectors | 1D Array |
| Matrix | 2D Array  |


In [22]:
#-Vector-#
a.shape

(3,)

In [23]:
#-Matrix-#
b.shape

(2, 3)

In [24]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

## Array Shapes

In [25]:
b.shape = (6,)

In [26]:
b

array([1., 2., 3., 4., 5., 6.])

In [27]:
b.shape = (3,2)

In [28]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [29]:
b.shape = (2,3)

In [30]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

### Utilities for Creating Arrays

In [31]:
np.arange?

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(2, 10, dtype=np.float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

**linspace** will create an array between starting and end values at some specified interval

In [35]:
np.linspace?

In [36]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

**zeros** produces a vector of zeros

In [37]:
np.zeros?

In [38]:
np.zeros(4)

array([0., 0., 0., 0.])

In [39]:
np.zeros(4, dtype=int) #Can specify dtype in many NumPy array creation tools

array([0, 0, 0, 0])

**empty** produces an unitialized array in memory that could contain any values

In [40]:
np.empty(3)

array([2., 4., 6.])

**identity** produces an identity matrix

In [41]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

## Array Indexing

**Documentation:** http://docs.scipy.org/doc/numpy/user/basics.indexing.html

For a 1-D array, indexing is the same as Python

In [42]:
z = np.linspace(1, 2, 5)

In [43]:
z

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [44]:
z[0]

1.0

In [45]:
z[0:2]

array([1.  , 1.25])

In [46]:
z[-1]

2.0

For 2D Arrays, the syntax is as follows

In [47]:
z = np.array([[1, 2], [3, 4]])

In [48]:
z

array([[1, 2],
       [3, 4]])

In [49]:
z[0, 0]

1

In [50]:
z[0, 1]

2

In [51]:
z[1, 0]

3

In [52]:
z[1, 1]

4

In [53]:
#-First Row-#
z[0,:]

array([1, 2])

In [54]:
#-Second Column (as an array)-#
z[:,1]

array([2, 4])

NumPy arrays of integers can also be used to extract elements

In [55]:
 z = np.linspace(2, 4, 5)

In [56]:
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [57]:
indices = np.array((0, 2, 3))

In [58]:
indices

array([0, 2, 3])

In [59]:
z[indices]

array([2. , 3. , 3.5])

You can also use a list of boolean values as a **mask**

In [60]:
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [61]:
d = np.array([0, 1, 1, 0, 0], dtype=bool)

In [62]:
d

array([False,  True,  True, False, False])

In [63]:
z[d]

array([2.5, 3. ])

Note that they are of the **same** length

In [64]:
len(z)

5

In [65]:
len(d)

5

In [66]:
d = np.array([0, 1, 1, 0, 0, 1], dtype=bool)

In [67]:
len(d)

6

In [68]:
z[d]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 6

## Array Methods

In [ ]:
 A = np.array((4, 3, 2, 1))

In [ ]:
A

In [ ]:
A.sort()

In [ ]:
A

In [ ]:
A.mean()

In [ ]:
A.sum()

In [ ]:
A.max()

In [ ]:
A.min()

In [ ]:
A.argmax()    #Index of the Maximum Element

In [ ]:
A.cumsum()   #Cumulative Sum

In [ ]:
A.cumprod()  #Cumulative Product

In [ ]:
A.var() 

In [ ]:
A.std() 

In [ ]:
A.shape = (2, 2)

In [ ]:
A

In [ ]:
A.T #Transpose

In [ ]:
A.transpose()  #Same as A.T

Another method worth knowing about is **searchsorted**

If $z$ is a nondecreasing array, then **z.searchsorted(a)** returns index of first $z$ in $z$ such that $z >= a$

In [ ]:
z = np.linspace(2, 4, 5)  

In [ ]:
z  #Non-Decreasing Array

In [ ]:
z.searchsorted(2.2)

In [ ]:
z.searchsorted(2.5)

In [ ]:
z.searchsorted(2.6)

It is also worth noting that many of these **methods** are also available as **NumPy functions**

In [ ]:
a = np.array((4, 3, 2, 1))

In [ ]:
np.mean(a)

# Operations Arrays

## Algebraic Operations

The algebraic operators +, -, *, / and ** all act elementwise on arrays

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
b = np.array([5, 6, 7, 8])

In [ ]:
a + b

In [ ]:
a * b

In [ ]:
a + 10    #Be careful with Broadcasting

Similar for 2D

In [ ]:
a = np.array([1, 2, 3, 4]).reshape((2,2))

In [ ]:
a

In [ ]:
b = np.array([5, 6, 7, 8]).reshape((2,2))

In [ ]:
b

In [ ]:
a + b

In [ ]:
a - b

In [ ]:
a + 10

**Warning:** The following is elementwise and is **not** matrix multiplication

In [ ]:
a * b 

**Matrix Multiplication**

In [ ]:
np.dot(a,b)

In [ ]:
# Python syntax for matrix multiplication
a @ b

## Array Comparison

As a rule comparisons are generally done elementwise

In [ ]:
z = np.array([2, 3])

In [ ]:
y = np.array([2, 3])

In [ ]:
z == y

In [ ]:
y[0] = 5

In [ ]:
z == y

The standard comparisons can also be used !=, >, <, >=, <= ...

You can also compare against scalars in a vectorized fashion

In [ ]:
z >= 3

And can be used for **conditional** extraction

In [ ]:
z[z >= 3]

## Broadcasting Functions

NumPy provides versions of the standard functions **log**, **exp**, **sin**, etc. that act elementwise on arrays

In [ ]:
z = np.array([1, 2, 3])

In [ ]:
np.sin(z)

In [ ]:
# Broadcasting enables not having to write loops
y = np.zeros(3)
for i in range(len(z)):
    y[i] = np.sin(z[i])

In [ ]:
y

In [ ]:
z

In [ ]:
#-vectorized operations in an expression
(1 / np.sqrt(2 * np.pi)) * np.exp(- 0.5 * z**2)