# Introduction to NumPy

## Why use NumPy?

1. Performance Improvements (Execution and Memory Usage)
1. More convenient math syntax
1. Enables vectorisation in low level `C`, `Fortran` code.

**Note:** For `data` work you will implicitly be using `numpy` through `pandas` and many other packages.

### Pure Python

In [1]:
import random
random.normalvariate(0,1)

-1.2436052931409238

In [2]:
length = 1000
a = [random.normalvariate(0,1) for x in range(length)]
b = [random.normalvariate(0,1) for x in range(length)]

**Question:** What is random.normalvariate?

In [3]:
random.normalvariate?

In [4]:
len(a), len(b)

(1000, 1000)

In [5]:
type(a), type(b)

(list, list)

In [6]:
# What is in list a
a

[0.3405292632549562,
 1.1729662582686413,
 1.376584399878448,
 -1.7300355631816204,
 -0.7068704092192556,
 0.23264401219332637,
 -0.4254800292536387,
 0.38308026919634613,
 2.1233410503159273,
 0.21252499216993898,
 0.14787865391421873,
 -0.8700520708729957,
 0.7400531726750528,
 -0.2460990237449914,
 -0.15990493072082013,
 0.6657927522723497,
 -0.23777473758774034,
 -1.390667015284836,
 0.10526286762588151,
 2.0782551745823725,
 0.42878013307156493,
 -0.24534082866895332,
 -1.42324713236291,
 -0.14294075942665568,
 0.2969725176009323,
 1.417825321356231,
 0.012879226298629878,
 -0.2919618078324547,
 -1.5296438106643648,
 -0.8332524310217169,
 -0.7346546434876302,
 0.22985087326986714,
 -0.8663075210540354,
 -1.7487500053135605,
 -1.328139952511383,
 -0.07112218965886088,
 -1.4462257300327583,
 1.2108058899581997,
 -0.30541991028134896,
 1.136686602439399,
 -1.7459543805250686,
 -1.180954205977293,
 2.167451047274052,
 1.5278188460702369,
 -2.132268621424332,
 1.036706220335019,
 -0.15

Let's multiply each element between a and b

In [7]:
%%timeit
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])

161 µs ± 7.46 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## NumPy

Let us now do the same excercise using NumPy

In [8]:
import numpy as np
np_a = np.array(a)
np_b = np.array(b)

In [9]:
type(np_a)

numpy.ndarray

In [10]:
len(np_a)

1000

In [11]:
np_a.shape

(1000,)

In [12]:
# What is in the np_a array
np_a

array([ 3.40529263e-01,  1.17296626e+00,  1.37658440e+00, -1.73003556e+00,
       -7.06870409e-01,  2.32644012e-01, -4.25480029e-01,  3.83080269e-01,
        2.12334105e+00,  2.12524992e-01,  1.47878654e-01, -8.70052071e-01,
        7.40053173e-01, -2.46099024e-01, -1.59904931e-01,  6.65792752e-01,
       -2.37774738e-01, -1.39066702e+00,  1.05262868e-01,  2.07825517e+00,
        4.28780133e-01, -2.45340829e-01, -1.42324713e+00, -1.42940759e-01,
        2.96972518e-01,  1.41782532e+00,  1.28792263e-02, -2.91961808e-01,
       -1.52964381e+00, -8.33252431e-01, -7.34654643e-01,  2.29850873e-01,
       -8.66307521e-01, -1.74875001e+00, -1.32813995e+00, -7.11221897e-02,
       -1.44622573e+00,  1.21080589e+00, -3.05419910e-01,  1.13668660e+00,
       -1.74595438e+00, -1.18095421e+00,  2.16745105e+00,  1.52781885e+00,
       -2.13226862e+00,  1.03670622e+00, -1.51946213e-01,  2.55167932e-01,
       -2.09851152e+00, -3.33785121e-01, -1.12716113e-01, -1.80074372e-01,
       -7.98189717e-01,  

In [13]:
%%timeit
np_c = np_a * np_b # Element by Element Operation for Multiply

1.05 µs ± 110 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


**Question:** Why does this seem to take longer? (Hint: What do you think `timeit` is doing?)

## Broadcasting

Broadcasting describes the absence of any explicit looping in `python`. 

Therefore you do not need to write explicit loops. 

In the code cell `above` the * operator performs the operations over the length of the arrays. 

In [14]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b                          # No Python Loop Required

array([2., 4., 6.])

NumPy has different behaviour when the **shapes of objects do not match**. 

For example, a `scalar` multiplied with an `array` will broadcase the operation along the array

**Documentation:** http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#module-numpy.doc.broadcasting

In [15]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

**Tip:** Using `numpy` is largely about learning how the operators behave in context. It is always worth doing some sense checking of your code.

# NumPy Data Types

NumPy supports a much greater variety of numeric data types than Python does

| Data type |	Description |
| ----------|---------------|
| bool_ |	Boolean (True or False) stored as a byte |
| int_  |	Default integer type (same as C long; normally either int64 or int32) |
| intc  |	Identical to C int (normally int32 or int64) |
| intp	 | Integer used for indexing (same as C ssize_t; normally either int32 or int64) |
| int8	 | Byte (-128 to 127) |
| int16 | 	Integer (-32768 to 32767) |
| int32 | 	Integer (-2147483648 to 2147483647) |
| int64 | 	Integer (-9223372036854775808 to 9223372036854775807) |
| uint8 | 	Unsigned integer (0 to 255) |
| uint16 |	Unsigned integer (0 to 65535) |
| uint32 |	Unsigned integer (0 to 4294967295) |
| uint64 |	Unsigned integer (0 to 18446744073709551615) |
| float_ |	Shorthand for float64. |
| float16 |	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa |
| float32 |	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa |
| float64 |	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa |
| complex_ |	Shorthand for complex128. |
| complex64	| Complex number, represented by two 32-bit floats (real and imaginary components) |
| complex128 |	Complex number, represented by two 64-bit floats (real and imaginary components) |

**Documentation:** http://docs.scipy.org/doc/numpy/user/basics.types.html

In [16]:
#Default dtypes are typically float64, int64 on most recent platforms
a = np.arange(4)

In [17]:
a

array([0, 1, 2, 3])

In [18]:
type(a[0])

numpy.int64

In [19]:
a = np.arange(4.0)

In [20]:
type(a[0])

numpy.float64

You do have control **over** dtypes in numpy should you need it:

In [21]:
a = np.arange(4, dtype=np.int16)

In [22]:
type(a[0])

numpy.int16

## Array Creation

Arrays can be generated from python sequences such as a List

In [23]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])

## Array Shapes

`NumPy` is really an n-dimensional (**nd**array), where vectors and matrices are just low dimensional cases

| Type | Dimension |
|---------|----------|
| Vectors | 1D Array |
| Matrix | 2D Array  |


In [24]:
#-Vector-#
a.shape

(3,)

In [25]:
b = np.array([[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0]])

In [26]:
#-Matrix-#
b.shape

(2, 3)

In [27]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

## Array Shapes

In [28]:
b.shape = (6,)

In [29]:
b

array([1., 2., 3., 4., 5., 6.])

In [30]:
b.shape = (3,2)

In [31]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [32]:
b.shape = (2,3)

In [33]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

### Utilities for Creating Arrays

In [34]:
np.arange?

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(2, 10, dtype=np.float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [37]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

**linspace** will create an array between starting and end values at some specified interval

In [38]:
np.linspace?

In [39]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

**zeros** produces a vector of zeros

In [40]:
np.zeros?

In [41]:
np.zeros(4)

array([0., 0., 0., 0.])

In [42]:
np.zeros(4, dtype=int) #Can specify dtype in many NumPy array creation tools

array([0, 0, 0, 0])

**empty** produces an unitialized array in memory that could contain any values

In [43]:
np.empty(3)

array([2., 4., 6.])

**identity** produces an identity matrix

In [44]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

## Array Indexing

**Documentation:** http://docs.scipy.org/doc/numpy/user/basics.indexing.html

For a 1-D array, indexing is the same as Python

In [45]:
z = np.linspace(1, 2, 5)

In [46]:
z

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [47]:
z[0]

1.0

In [48]:
z[0:2]

array([1.  , 1.25])

In [49]:
z[-1]

2.0

In [50]:
z[-2:]

array([1.75, 2.  ])

For 2D Arrays, the syntax is as follows

In [51]:
z = np.array([[1, 2], [3, 4]])

In [52]:
z

array([[1, 2],
       [3, 4]])

In [53]:
z[0, 0]

1

In [54]:
z[0, 1]

2

In [55]:
z[1, 0]

3

In [56]:
z[1, 1]

4

In [57]:
#-First Row-#
z[0,:]

array([1, 2])

In [58]:
#-Second Column (as an array)-#
z[:,1]

array([2, 4])

NumPy arrays of integers can also be used to extract elements

In [59]:
 z = np.linspace(2, 4, 5)

In [60]:
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [61]:
indices = np.array((0, 2, 3))

In [62]:
indices

array([0, 2, 3])

In [63]:
z[indices]

array([2. , 3. , 3.5])

You can also use a list of boolean values as a **mask**

In [64]:
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [65]:
d = np.array([0, 1, 1, 0, 0], dtype=bool)

In [66]:
d

array([False,  True,  True, False, False])

In [67]:
z[d]

array([2.5, 3. ])

Note that they are of the **same** length

In [68]:
len(z)

5

In [69]:
len(d)

5

In [70]:
d = np.array([0, 1, 1, 0, 0, 1], dtype=bool)

In [71]:
len(d)

6

In [72]:
z[d]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 6

## Array Methods

In [73]:
 A = np.array((4, 3, 2, 1))
    

In [74]:
A

array([4, 3, 2, 1])

In [75]:
A.sort()

In [76]:
A

array([1, 2, 3, 4])

In [77]:
A.mean()

2.5

In [78]:
A.sum()

10

In [79]:
A.max()

4

In [80]:
A.min()

1

In [81]:
A.argmax()    #Index of the Maximum Element

3

In [82]:
A.cumsum()   #Cumulative Sum

array([ 1,  3,  6, 10])

In [83]:
A.cumprod()  #Cumulative Product

array([ 1,  2,  6, 24])

In [84]:
A.var() 

1.25

In [85]:
A.std() 

1.118033988749895

In [86]:
A.shape = (2, 2)

In [87]:
A

array([[1, 2],
       [3, 4]])

In [88]:
A.T #Transpose

array([[1, 3],
       [2, 4]])

In [89]:
A.transpose()  #Same as A.T

array([[1, 3],
       [2, 4]])

Another method worth knowing about is **searchsorted**

If $z$ is a nondecreasing array, then **z.searchsorted(a)** returns index of first $z$ in $z$ such that $z >= a$

In [90]:
z = np.linspace(2, 4, 5)  

In [91]:
z  #Non-Decreasing Array

array([2. , 2.5, 3. , 3.5, 4. ])

In [92]:
z.searchsorted(2.2)

1

In [93]:
z.searchsorted(2.5)

1

In [94]:
z.searchsorted(2.6)

2

It is also worth noting that many of these **methods** are also available as **NumPy functions**

In [95]:
a = np.array((4, 3, 2, 1))

In [96]:
np.mean(a)

2.5

# Operations Arrays

## Algebraic Operations

The algebraic operators +, -, *, / and ** all act elementwise on arrays

In [97]:
a = np.array([1, 2, 3, 4])

In [98]:
b = np.array([5, 6, 7, 8])

In [99]:
a + b

array([ 6,  8, 10, 12])

In [100]:
a * b

array([ 5, 12, 21, 32])

In [101]:
a + 10    #Be careful with Broadcasting

array([11, 12, 13, 14])

Similar for 2D

In [102]:
a = np.array([1, 2, 3, 4]).reshape((2,2))

In [103]:
a

array([[1, 2],
       [3, 4]])

In [104]:
b = np.array([5, 6, 7, 8]).reshape((2,2))

In [105]:
b

array([[5, 6],
       [7, 8]])

In [106]:
a + b

array([[ 6,  8],
       [10, 12]])

In [107]:
a - b

array([[-4, -4],
       [-4, -4]])

In [108]:
a + 10

array([[11, 12],
       [13, 14]])

**Warning:** The following is elementwise and is **not** matrix multiplication

In [109]:
a * b 

array([[ 5, 12],
       [21, 32]])

**Matrix Multiplication**

In [110]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [111]:
# Python syntax for matrix multiplication
a @ b

array([[19, 22],
       [43, 50]])

## Array Comparison

As a rule comparisons are generally done elementwise

In [112]:
z = np.array([2, 3])

In [113]:
y = np.array([2, 3])

In [114]:
z == y

array([ True,  True])

In [115]:
y[0] = 5

In [116]:
z == y

array([False,  True])

The standard comparisons can also be used !=, >, <, >=, <= ...

You can also compare against scalars in a vectorized fashion

In [117]:
z >= 3

array([False,  True])

And can be used for **conditional** extraction

In [118]:
z[z >= 3]

array([3])

## Broadcasting Functions

NumPy provides versions of the standard functions **log**, **exp**, **sin**, etc. that act elementwise on arrays

In [119]:
z = np.array([1, 2, 3])

In [120]:
np.sin(z)

array([0.84147098, 0.90929743, 0.14112001])

In [121]:
# Broadcasting enables not having to write loops
y = np.zeros(3)
for i in range(len(z)):
    y[i] = np.sin(z[i])

In [122]:
y

array([0.84147098, 0.90929743, 0.14112001])

In [123]:
z

array([1, 2, 3])

In [124]:
#-vectorized operations in an expression
(1 / np.sqrt(2 * np.pi)) * np.exp(- 0.5 * z**2)

array([0.24197072, 0.05399097, 0.00443185])